services:
  # Composer
  composer:
    image: composer/composer
    volumes:
      - ./:/app
  # Web
  web:
    build:
      image: karllhughes/colleges
      dockerfile: Dockerfile
    links:
      - database
    volumes:
      - ./vendor:/var/www/html/vendor
  # Docker deployer
  deployer:
    image: chickenzord/hyper
    volumes:
      - docker:/docker
    encrypted_env_file: docker/deployer/.env.encrypted
