version: "3.0"
services:

  # Nginx Proxy
  nginx:
    image: nginx
    restart: always
    links:
      - api
    ports:
      - 32000:80
    volumes:
      - ./config/nginx:/etc/nginx/conf.d

  # API Service
  api:
    image: shiphp/shiphp-crud-api
    restart: always
    links:
      - database
    env_file: .env

  # Database
  database:
    image: postgres:9.5
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
    volumes:
      - ./.data:/var/lib/postgresql/data
