version: "2"
services:

  # API Service
  api:
    size: s3
    image: karllhughes/colleges
    restart: always
    links:
      - database
    # env_file:
    #   - ../.env
    ports:
      - 80:80

  # Database
  database:
    size: s3
    image: postgres:9.5
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
    volumes:
      - colleges:/var/lib/postgresql/data
