version: "2"
services:

  # API Service
  api:
    size: s3
    image: karllhughes/colleges
    restart: always
    links:
      - database
    environment:
      - DB_ADAPTER=pgsql
      - DB_ENGINE=PostgreSQL
      - DB_HOSTNAME=database
      - DB_DATABASE=admin
      - DB_USERNAME=admin
      - DB_PASSWORD=
      - DB_PORT=5432
    ports:
      - 80:80

  # Database
  database:
    size: s3
    image: postgres:9.5
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
    volumes:
      - colleges:/var/lib/postgresql/data
