version: "2"
services:

  # API Service
  api:
    build: ../.
    restart: always
    links:
      - database
    environment:
      - DB_ADAPTER=pgsql
      - DB_ENGINE=PostgreSQL
      - DB_HOSTNAME=database
      - DB_DATABASE=admin
      - DB_USERNAME=admin
      - DB_PASSWORD=
      - DB_PORT=5432
    volumes:
      - ../.:/var/www/html
    ports:
      - 8100:80

  # Database
  database:
    image: postgres:9.5
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
    volumes:
      - ../.data:/var/lib/postgresql/data
